### ISSUE TITLE
Help with SPICE setup for ALE

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/ale#430]
Please either post (or point me to) how I can grab SPICE for ALE. If not available locally, it would be nice to have SPICE available locally for others too.

**Comment by jessemapel** [comment]
@thareUSGS All ALE needs is a copy of the PDS SPICE repos with the meta-kernels updated. For example if you want to stage the Messenger spice at `/scratch/spice` here's how you would do it.

Download [the spice data from Naif](https://naif.jpl.nasa.gov/pub/naif/pds/data/mess-e_v_h-spice-6-v1.0/) into `/scratch/spice`. You want to have `/scratch/spice/messsp_1000`.


Update the paths in the metakernels located at `messsp_1000/extras/mk/`. They should have a section that looks like this from [msgr_2004_v13.tm](https://naif.jpl.nasa.gov/pub/naif/pds/data/mess-e_v_h-spice-6-v1.0/messsp_1000/extras/mk/msgr_2004_v13.tm):

```
\begindata

      PATH_VALUES     = ( './data' )

      PATH_SYMBOLS    = ( 'KERNELS' )

      KERNELS_TO_LOAD = (


                          '$KERNELS/lsk/naif0011.tls'

                          '$KERNELS/pck/pck00010_msgr_v23.tpc'

                          '$KERNELS/sclk/messenger_2548.tsc'

                          '$KERNELS/fk/msgr_dyn_v600.tf'
                          '$KERNELS/fk/msgr_v231.tf'

                          '$KERNELS/ik/msgr_epps_v100.ti'
                          '$KERNELS/ik/msgr_grns_v110.ti'
                          '$KERNELS/ik/msgr_mag_v021.ti'
                          '$KERNELS/ik/msgr_mascs_v100.ti'
                          '$KERNELS/ik/msgr_mdis_v160.ti'
                          '$KERNELS/ik/msgr_mla_v010.ti'
                          '$KERNELS/ik/msgr_rs_v111.ti'
                          '$KERNELS/ik/msgr_xrs_v001.ti'

                          '$KERNELS/spk/msgr_antenna_v000.bsp'
                          '$KERNELS/spk/msgr_040803_150430_150430_od431sc_2.bsp'

                          '$KERNELS/ck/msgr_0408_v04.bc'
                          '$KERNELS/ck/msgr_0409_v04.bc'
                          '$KERNELS/ck/msgr_0410_v04.bc'
                          '$KERNELS/ck/msgr_0411_v04.bc'
                          '$KERNELS/ck/msgr_0412_v04.bc'
                          '$KERNELS/ck/msgr_mdis_gm040819_150430v1.bc'

                        )

   \begintext
```

What you need to do is update the `PATH_VALUES     = ( './data' )` keyword so that it points to where you installed your spice data. In the example of `/scratch/spice` you would change it to `PATH_VALUES     = ( '/scratch/spice/messsp_1000/data' )`.

Finally, set `ALESPICEROOT` to where you have your spice data. In our example you would do `ALESPICEROOT=/scratch/spice/`.

You can see a little more info in the [docs](https://ale.readthedocs.io/en/latest/library/python/mix_ins/supplementary_data.html#ale.base.data_naif.NaifSpice.kernels)

**Comment by thareUSGS** [comment]
finally downloaded from NAIF (took a while), updated paths, and tested ALE using HiIRSE and LROC. Thanks for the tips.
