### ISSUE TITLE
Add Python 3.10+ support

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/ale#496]
When attempting to run using Python 3.10 and 3.11, I am seeing the following:

`AttributeError: module 'collections' has no attribute 'Mapping'`. In 3.9 and lower, we get a warning about the upcoming deprecation. Please consider adding 3.10 support.

**Comment by antonhibl** [comment]
I just tested the compiling of Ale using Python3.10 and it seems this has been addressed by implementing the logic between Python versions to handle this import. In Python 3.10 and above it needs to be `from collections.abc import Mapping` and for Python 3.9 and below it requires `from collections import Mapping`. The logic in util.py was altered to be:

```
try:
    from collections.abc import Mapping
except ImportError:
    from collections import Mapping
```

I have tested building and installing Ale using both versions of Python and it seems to be fixed. The python versions lower than 3.9 may still give these warning regarding the upcoming depreciation but the logic should be implemented for it to function in 3.10 and above. If this issue is appearing somewhere besides building/installing perhaps this import is in another file, will need steps to re-create if that is the case.

**Comment by antonhibl** [comment]
python 3.11 seems to require using `python3.11 -m pip install .` in order to install ale although it still gives several depreciation warnings. It does install correctly so for now I will mark this as closed but note that we need to transfer from `setup.py` to `pyproject.toml` as well as include the `wheel` package as a dependency. Currently I am using pip 22.3 for python3.11, the recommendation going forward though is that pip 23.1 will enforce this behaviour change and not allow `setup.py install`. A possible replacement is to enable the '--use-pep517' option. more discussion on these changes are found [here](https://github.com/pypa/pip/issues/8559).

**Comment by jlaura** [comment]
:+1: I check this out this morning, created a new conda environment with python 3.11, python setup.py install on a master branch clone of ale, and ran pytest. conda downgrades python to 3.10, presumably because of an ale dependency and pytest passes with no issues. So, I concur that this is done for now.

I can only guess that the original issue was because some other package was not yet upgraded to 3.10/3.11. 

Thanks @antonhibl  for checking this!

**Comment by antonhibl** [comment]
changes supporting the move to pyproject.toml and setup.cfg in accordance with the recommended build changes away from setup.py have been made at [this PR](https://github.com/USGS-Astrogeology/ale/pull/510).
