### ISSUE TITLE
Add light-time support to Ale.

### ISSUE THREAD

**Issue by kberryUSGS** [USGS-Astrogeology/ale#77]
ISIS optionally allows light-time correction (adjustment for the time it takes the light to travel from the target to the detector) and more. (see `abcorr` under: ftp://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/cspice/spkez_c.html.) Does it make sense to support anything like this in Ale?

**Comment by jlaura** [comment]
I was under the impression that we really need to support this inside of the sensor and not on the ephemeris information coming in, but I would love to learn more about where it is most appropriate to do and why!

**Comment by kberryUSGS** [comment]
@jlaura Dealing with this in the sensor sounds totally reasonable to me. I'm still trying to get the "division of responsibilities" down, as I keep lumping in ale's functionalities in with "spice usually takes care of this" but that's not really correct.

**Comment by kberryUSGS** [comment]
Talked to @jessemapel and this does need to be added, so changed ticket title.

**Comment by jessemapel** [comment]
To add some more context. To hand light time correctly, we should be accounting for it in the sensor model, but right now ISIS is not. Instead, ISIS has SPICE handle it during the spkezr calls in spiceinit. In order to support current functionality, we should be matching those spkezr calls. ISIS handles this as a kernel variable in the IAKs (`INS<ik code>_LIGHTTIME_CORRECTION`). We can handle this in ALE by adding a property to data_naif that is passed into spkezr for light time correction. Then, concrete drivers that use data_isis can set it as they please.

**Comment by jessemapel** [comment]
In short, we should be using the `LT+S` adjustments from [SPICE](https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/req/abcorr.html) whenever we compute where the sensor is relative to the target in USGSCSM. This way, we can account for things like highly oblique imagery where the light time to the surface changes significantly across the image.

**Comment by jessemapel** [comment]
Based on https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/base/objs/Spice/LightTimeCorrectionState.cpp, it looks like ISIS defaults to `LT+S`
